server:
  port: 8080

info:
  app:
    name: "Biblioteca de Publicação de Livros"
    description: "Uma plataforma para autores publicarem, gerenciarem e compartilharem seus livros com leitores. Facilita o acesso a obras literárias e incentiva a criação e divulgação de novos talentos."
    version: "1.0.0"

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html

app:
  file-storage-location: "target/uploaded_files"
