server:
  port: 8080
info:
  app:
    name: Proj Facul
    description: Demo project for Spring Boot
    version: 0.0.1-SNAPSHOT
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html